### ISSUE TITLE
  How to solve the error:'Grid3d::m_grid' is not a variable in clause 'shared'

### ISSUE THREAD

**Issue by hsiaochao** [robotics-upo/dll#15]
Hello, I encountered the following error while compiling the project and would like to know how to solve it. Thank you!
error:
/root/catkin_ws/src/dll-main/src/grid3d.hpp:640:59: error: 'Grid3d::m_grid' is not a variable in clause 'shared'
In file included from /root/catkin_ws/src/dll-main/src/dllnode.hpp:19:0,
                 from /root/catkin_ws/src/dll-main/src/dll_node.cpp:3:
/root/catkin_ws/src/dll-main/src/grid3d.hpp: In member function 'void Grid3d::computeGrid()':
/root/catkin_ws/src/dll-main/src/grid3d.hpp:640:59: error: 'Grid3d::m_grid' is not a variable in clause 'shared'
In file included from /root/catkin_ws/src/dll-main/src/grid3d_node.cpp:3:0:

**Comment by fercabe** [comment]
Hi, the software is intended for C++14 and ubuntu 20.04. Please, provide more information: What is your configuration? which ROS are you using?

**Comment by hsiaochao** [comment]
oh，I use gcc 5.4.0 and ubuntu 16.04, gcc 5.4.0 supports c++11 and should not support c++14, which may be the reason for this issue.
I tried using DLL v1.0 and was able to complete the compilation.
Thank you!
