### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by MIke-1118** [robotics-upo/dll#5]
I'm sorry to bother you. I have no idea that how can i run the program. Can you tell me the relevant instructions? Thanks!

**Comment by MartinEekGerhardsen** [comment]
If you download e.g. airsim1.bag you should be able to execute `roslaunch dll airsim1.launch` from your catkin folder. You might have to change the bag-player line to include the path to your bagfile though, e.g. `<node name="bag_player" type="play" pkg="rosbag" args="/my/path/to/data/airsim1.bag -s 0 -r 1.0 --clock " />`.

**Comment by MIke-1118** [comment]
Thank you very much！I have  went through the steps you said， but I could not see anything in rviz and it only shows that “Grid map successfully saved on ……”. Is this grid map the grid map of the Prior map？And how can i use it to locate？Could you give me a reply？Thanks！

**Comment by MIke-1118** [comment]
And how can i evaluate its accuracy? Where is it's truth？

**Comment by MartinEekGerhardsen** [comment]
Yes the grid map is the prior map. Could you post some screenshots of what you see on rviz, and copy the text you see in the terminal? You need to first wait for the map to be converted into the grid map, which can take _a lot_ of time (but once completed this grid is stored so you don't have to do it again), but you should see a percentage of you completion in the terminal. Rviz should start showing the map and frames once the grid is generated, and a pre-configured rviz will be launched by the launch file, which should ensure that you should see the map and the frames moving in it. 

The ground truth will probably depend on which dataset you are using. The airsim datasets include the topic `/airsim_node/drone_1/odom_local_ned`, which I think is the airsim ground truth (though I can be wrong, it will probably be better to wait for some of the people who wrote this package to chime in, or you can watch this topic yourself to see if it seems like the ground truth).

**Comment by fercabe** [comment]
Hi all,

Martin answered very well all questions. Just to add that the ground truth poses are in "/airsim_node/drone_1/odom_local_ned" for airsim bags, and in "/ground_truth/pose" for the catec bags.

Mike, if everything is clear, please close this issue.

Fernando
