### ISSUE TITLE
How are prior maps generated? What is the suffix of the map? 

### ISSUE THREAD

**Issue by MIke-1118** [robotics-upo/dll#8]
I‘m sorry to bother you again ！How are prior maps generated? What is the suffix of the map? Thanks！

**Comment by MartinEekGerhardsen** [comment]
Depends on what you mean? You start off with a .bt type extension (if you use one of the example datasets from this package, there should be such a file in `dll/maps`). Then, when the program is started, the program looks for the map file you specified, e.g. `my_map.bt`. Then it checks if there exists a file in the same location called `my_map.grid`. If it doesn't exist, then the program starts essentially converting the `my_map.bt` data to `my_map.grid`, which might take a long time, and stores the `my_map.grid` file in the same folder as `my_map.bt`. The next time the program starts, it doesn't have to compute the grid map. 

If you want to generate a prior map for some other projects than the examples given here, then you'd have to research that further depending on the use case. The most important thing is to convert whatever map you have to a .bt file (you can do this with e.g. PCL if you have some other point cloud file), or you'll have to rewrite the part of this package which reads in the .bt file to read in your map.

**Comment by MIke-1118** [comment]
thanks a lot ! If i only have a .pcd file. How can i transform it to a .bt file?

**Comment by MartinEekGerhardsen** [comment]
I found [this](https://github.com/HaowenLai/pcd2octomap) online, which should do the trick, though I haven't tried it myself. Otherwise, you can try writing something yourself. .bt is an octomap-file, so you'll have to check out how to read in a .pcd file (e.g. using PCL) then how to convert from that to an octomap OcTree and then you can store it as a .bt file.

**Comment by MIke-1118** [comment]
thanks a lot. And how did you get a .bt file?

**Comment by MartinEekGerhardsen** [comment]
I just happened to have one for the project I was working on :shrug:

**Comment by MIke-1118** [comment]
hello！I’m here again！What is the resolution set for your octomap？And Is a .ot file ok?

**Comment by MartinEekGerhardsen** [comment]
Looks like both .ot and .bt are supported in the code :+1: Not entirely sure of the resolution, but you should choose this depending on the size of your map. If it is several kilometres and you use a very small resolution then it would probably be very slow. I'd suggest trying something that seems reasonable to you and testing that.

**Comment by fercabe** [comment]
Hi,

Both, .bt and .ot are supported as presentation of the map. The resolution is actually a design parameters of the mapping process. In most of my experiments, a resolution of 0.05m is a good choice. Remember that most of the LIDARs in the market has an accuracy of 3 to 5 cm, so setting the resolution to 0.05 is a good trade-off.

Regarding how to create the .bt or .ot, please, take a look to octomap. It is fully integrated into ROS, and very easy to use. If you don't have a map, you will need to implement the full mapping pipeline: data gathering, SLAM and mapping. We cannot help regarding this, but you can find lot and lot of documentation in internet.

I close this issue.
Fernando
