### ISSUE TITLE
Run other datasets

### ISSUE THREAD

**Issue by MIke-1118** [robotics-upo/dll#9]
hello！I saved a .ot file in `dll/maps.` And `<arg name="map" default="myown.ot" />` But when I run the program , it shows "NULL otcomap". How come？Where else do I need to set the path?

**Comment by fercabe** [comment]
Hi Mike,

In the example launch files you can find two arguments:
 - arg name="map" default="mbzirc.bt" 
 - arg name="map_path" default="$(find dll)/maps/$(arg map)"

The first one specifies the map name, the second the path. Just change "mbzirc.bt" for "myown.ot" and be sure that the map_path argument is properly set to right path.

If this does not work, just passme the .ot file and so I can check what is going on.

Fernando

**Comment by MIke-1118** [comment]
I'm sorry it didn't work. How can i pass the .ot file to you ?

**Comment by fercabe** [comment]
Just upload the file somewhere and pass me the link through a comment.

Fernando

**Comment by MIke-1118** [comment]
https://github.com/MIke-1118/kitti
The .ot file is here and could you check it for me, please

**Comment by fercabe** [comment]
Hi,

I can see the problem. The point-cloud is so large that there is a memory allocation exception. The only way to solve this is by reducing the size or the resolution of the point-cloud. 

But, even if octomap is able to load it, be aware that the Ditance Field grid will require muuuuch more memory. Your point cloud approximately covers a volume of 350x340x35 meters, at 0.1m resolution, you will need at least 30GB of free space in RAM..... only for the grid.

DLL works well no matter the maps, but you have to solve all the particularities related with your possible hardware limitations. You can divide the map in small pieces, loading the proper map when required and dealing with the handshaking between maps, but this will require for new software development.

Fernando

**Comment by MIke-1118** [comment]
Thanks a lot，This is a real headache.
